import { Router } from "express";
import authRoutes from "../api/auth/index.js";
import userRoutes from "../api/user/index.js";
import seminarRoute from "../api/seminar/index.js";
import applyRoute from "../api/Apply/index.js";
const router = Router();
router.use("/auth", authRoutes);
router.use("/user", userRoutes);
router.use("/seminar", seminarRoute);
router.use("/apply", applyRoute);
export default router;
