import { Router } from "express";
import authRoutes from "../api/auth/index.js";
import userRoutes from "../api/user/index.js";
import seminarRoute from "../api/seminar/index.js";
import applyRoute from '../api/apply/index.js';
import mailRoute from "../api/mail/index.js";
import addressRoute from "../api/address/index.js";
const router = Router();
router.use("/auth", authRoutes);
router.use("/user", userRoutes);
router.use("/seminar", seminarRoute);
router.use("/apply", applyRoute);
router.use("/mail", mailRoute);
router.use("/address", addressRoute);
export default router;
